CREATE TABLE correntista (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome                  VARCHAR(255)  NOT NULL,
    documentocpfoucnpj    VARCHAR(14)   NOT NULL,
    email                 VARCHAR(255)  NOT NULL,
    telefone              VARCHAR(25),
    PRIMARY KEY (id),
    CONSTRAINT uk_correntista_documento UNIQUE (documentocpfoucnpj)
);
CREATE TABLE conta (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo              VARCHAR(31)   NOT NULL,
    numero            VARCHAR(20)   NOT NULL,
    saldo             NUMERIC(19,2) NOT NULL,
    limite            NUMERIC(19,2),
    id_correntista    BIGINT        NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_conta_numero UNIQUE (numero),
    CONSTRAINT fk_conta_correntista FOREIGN KEY (id_correntista) REFERENCES correntista (id)
);

CREATE TABLE transacao (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo      VARCHAR(20)   NOT NULL,
    valor     NUMERIC(19,2) NOT NULL,
    data      TIMESTAMP     NOT NULL,
    contaid   BIGINT        NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_transacao_conta FOREIGN KEY (contaid) REFERENCES conta (id)
);